## **Loading and Knowing your data**

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
df = pd.read_csv(url, sep = '\t')

In [3]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### How many products cost more than $10.00?

In [4]:
df['item_price'] = df['item_price'].str.replace('$','',regex=False).astype(float)

In [5]:
df['price_per_item'] = df['item_price'] / df['quantity']
df.head()

,order_id,quantity,item_name,choice_description,item_price,price_per_item
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49

In [6]:
df_pro = (df['price_per_item'] > 10).sum()
df_pro

np.int64(1034)

###  What is the price of each item?

In [7]:
item_prices = df[['item_name', 'choice_description', 'price_per_item']].drop_duplicates()
item_prices

,item_name,choice_description,price_per_item
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",8.49
...,...,...,...
4602,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4607,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25

### Find the most expensive items ?

In [8]:
item_prices.sort_values(by = 'price_per_item', ascending = False)

,item_name,choice_description,price_per_item
2610,Carnitas Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
1159,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",11.89
4239,Carnitas Salad Bowl,"[Tomatillo Green Chili Salsa, [Black Beans, Ch...",11.89
1132,Carnitas Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",11.89
1311,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.89
...,...,...,...
162,Canned Soda,[Diet Coke],1.09
28,Canned Soda,[Dr. Pepper],1.09
51,Canned Soda,[Mountain Dew],1.09
126,Canned Soda,[Coca Cola],1.09
34,Bottled Water,NaN,1.09

### Sort by the name of the item

In [9]:
df.item_name.sort_values()

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

### What was the quantity of the most expensive item ordered?

In [10]:
df['item_price'].idxmax()

3598

In [11]:
df.loc[3598]

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
price_per_item                                2.95
Name: 3598, dtype: object

In [12]:
df.loc[df['item_price'].idxmax()]['quantity']

np.int64(15)

### How many times was a Veggie Salad Bowl ordered?

In [13]:
df[df['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

np.int64(18)

In [14]:
total_veggie_salads = df.groupby('item_name')['quantity'].sum()['Veggie Salad Bowl']
print(total_veggie_salads)

18

### How many times did someone order more than one Canned Soda?

In [15]:
df[(df['item_name']== 'Canned Soda') & (df['quantity'] > 1)].shape[0]

20

In [16]:
canned_soda_multi_orders = df[(df['item_name'] == 'Canned Soda') & (df['quantity'] > 1)]
len(canned_soda_multi_orders)

20