In [1]:
import pandas as pd
import numpy as np

In [2]:
url1 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv"
url2 = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv"

In [3]:
df1 = pd.read_csv(url1)
df2 = pd.read_csv(url2)

In [5]:
print(df1.head())
print(df2.head())

    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70
1  15.0          8           350        165    3693          11.5     70
2  18.0          8           318        150    3436          11.0     70
3  16.0          8           304        150    3433          12.0     70
4  17.0          8           302        140    3449          10.5     70

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN
1       1          buick skylark 320         NaN          NaN          NaN
2       1         plymouth satellite         NaN          NaN          NaN
3       1              amc rebel sst         NaN          NaN          NaN
4       1                ford torino         NaN          NaN          NaN

   Unnamed: 12  Unnamed: 13
0          NaN          NaN
1          NaN          NaN
2          NaN          NaN
3          NaN          NaN
4          NaN          NaN
    mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76
1  20.0          6           225        100    3651          17.7     76
2  18.0          6           250         78    3574          21.0     76
3  18.5          6           250        110    3645          16.2     76
4  17.5          6           258         95    3193          17.8     76

   origin                 car
0       3         honda civic
1       1      dodge aspen se
2       1   ford granada ghia
3       1  pontiac ventura sj
4       1       amc pacer d/l

### first dataset has some unnamed blank columns, fix df1

In [7]:
df1 = df1.loc[: , "mpg":"car"]
df1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### What is the number of observations in each dataset?

In [10]:
print(df1.shape)
print(df2.shape)

(198, 9)
(200, 9)

Join df1 and df2 into a single DataFrame called cars

In [12]:
cars = pd.concat([df1,df2])
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [20]:
car_owners = np.random.randint(1500, high=73001, size = 398, dtype=np.int32)
car_owners

array([68146, 40611,  5972,  2999, 28419, 18890, 32658,  6973, 24302,
       46211, 61251, 40396,  9410, 60997, 43686, 21339, 40011, 39703,
       49599, 43891, 63942,  3420, 15324, 30763,  2888, 18822, 33279,
       40812, 63207, 43323, 56192, 56880, 46310, 59129, 17338, 67791,
       48715, 24401, 60887, 26124, 18007, 72395, 62308, 37434,  7936,
       34806, 68995, 62170, 37643, 45601, 31032, 41492, 42357, 69793,
       10153, 18512, 54631, 65941, 63626, 44682,  9919,  2313, 10960,
       59772,  1896, 44410, 27600, 29169, 38880, 66342, 55222, 22076,
       58639, 70005, 60407, 69992, 23764,  2720, 11714,  2247, 62695,
        7765, 52970,  8100, 29627, 14819, 23053, 12110, 66611,  4745,
       46140, 53576, 26476, 59449, 37428, 48677, 65020,  5153, 71868,
       33175, 30340, 47906, 51341, 69722, 56363, 66067, 59546,  2476,
        5337, 52627, 65062, 31294, 47943,  3300, 62007,  9119, 70229,
       58882, 60187, 59586, 68207, 30837, 22489, 27183, 30016, 30965,
       18676, 33743, 14521, 10296, 10817, 62072, 22868, 50406, 64867,
       52241, 19989, 58263, 42606, 40521,  4613, 16581, 51639, 55607,
       41384,  9993, 42929,  6242,  8608, 24894, 50174, 24355, 18902,
       41476, 45383, 28456, 11274, 65356, 55173, 63215, 36172, 31901,
       71091, 25043, 64760, 62432, 39935, 21910, 49744, 61271,  6547,
       52286, 69610, 53725, 35019, 16224, 57788, 45467,  8589, 28772,
       31529, 59497, 47063,  6548, 55148,  1808, 11377, 11305, 33218,
        1617, 17877, 29849, 44780, 49948, 53002, 51802, 61868,  8342,
       64643, 72531, 29699, 24091,  3202, 18830, 30741, 16993, 69046,
       38527, 19699,  7865, 21439, 57823, 61102, 25770, 61087, 51169,
       49744, 32043, 44478,  1941, 67282, 43540, 50049, 57837,  6637,
       34677, 31533,  6804, 25315, 31871, 58395, 28856, 16905, 17552,
       19894, 72944,  9910, 29417, 67725, 14135, 27214, 44555,  8068,
       46855, 25571,  7007, 45364, 18304, 26407, 28302, 33992, 62213,
       21692, 50707, 35249, 66187, 33477, 56043, 66148,  7944, 14144,
       19957,  9760, 22676, 51002, 15671, 30942, 23867, 60872, 21231,
        2507, 40480, 36434, 71344, 24812,  8368, 66587, 17545, 68013,
       57691, 60364, 13243, 46566, 54783, 63560, 32378, 28588, 17900,
       33557,  7154, 60611, 14065, 42743, 16994, 11746, 35576, 61232,
       65290, 31511, 14623,  4726, 52081, 35291, 68734, 45149, 50540,
       52902, 40285, 37892, 50117, 51754, 41461, 18243, 66693, 23847,
       19764, 52107, 35984, 22504, 44468, 19732,  7443, 27686, 55599,
       32401, 56950, 44148, 20726, 62590,  8875,  8627, 33645, 38760,
       45513, 12146, 27706, 54428, 14273,  3662, 32707, 23049,  2248,
       25549, 70556,  8819, 33649, 11452, 46251,  4187, 45400, 61610,
       32844, 59506, 17745, 43834, 66795,  2304, 68718, 52998, 37741,
       39661, 49786, 15879, 40802, 17342, 45405, 20200, 68663, 12280,
       11321, 26585, 57782, 66470, 71186, 15577, 58229, 21513, 39656,
       10545, 31675, 40516, 38738, 69819,  8260, 67686, 64618, 72552,
        9064, 69749, 46427, 31103, 62781, 35160, 27033, 72459, 37011,
       46631, 40134], dtype=int32)

### Add the column owners to cars

In [23]:
cars["car_owners"] = car_owners
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,car_owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,68146
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,40611
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,5972
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,2999
4,17.0,8,302,140,3449,10.5,70,1,ford torino,28419