## **Loading and Knowing your data**

In [66]:
import pandas as pd
import numpy as np

In [67]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
df = pd.read_csv(url, sep = '\t')

In [68]:
df.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [69]:
df.tail()

,order_id,quantity,item_name,choice_description,item_price
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [70]:
df.shape

(4622, 5)

In [71]:
df.shape[0]

4622

In [72]:
df.shape[1]

5

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [74]:
df.memory_usage(deep = True)

Index                    132
order_id               36976
quantity               36976
item_name             297299
choice_description    422087
item_price            255340
dtype: int64

In [75]:
df.columns.to_list()

['order_id', 'quantity', 'item_name', 'choice_description', 'item_price']

In [76]:
df.index

RangeIndex(start=0, stop=4622, step=1)

### Most ordered Item

In [77]:
most_ordered = df.groupby('item_name')['quantity'].sum().sort_values(ascending=False)

In [78]:
most_ordered.head(1)

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Which item was included in the most orders

In [79]:
frequency = df['item_name'].value_counts()
frequency.head(1)

item_name
Chicken Bowl    726
Name: count, dtype: int64

### What was the most ordered item in the choice_description column?

In [80]:
most_ordered = df.groupby('choice_description')['quantity'].sum().sort_values(ascending=False)
most_ordered.head(1)

choice_description
[Diet Coke]    159
Name: quantity, dtype: int64

### How many items were orderd in total?

In [81]:
total_item = df.quantity.sum()
total_item

np.int64(4972)

### Turn the item price into a float

In [82]:
df.item_price.dtype

dtype('O')

In [83]:
df['item_price'] = df.item_price.str.replace('$', '', regex=False).str.strip().astype(float)

In [84]:
df.item_price.dtype

dtype('float64')

### How much was the revenue for the period in the dataset?

In [85]:
revenue = (df['quantity'] * df['item_price']).sum()
revenue

np.float64(39237.02)

### How many orders were made in the period?

In [86]:
df.order_id.value_counts().count()

np.int64(1834)

### What is the average revenue amount per order?

In [87]:
revenue = (df['quantity'] * df['item_price']).sum()
order_count = df.order_id.nunique() 
average_revenue_per_order = revenue / order_count

average_revenue_per_order

np.float64(21.39423118865867)

### How many different items are sold?

In [88]:
df.item_name.nunique()

50