In [1]:
import pandas as pd
import numpy as np

In [2]:
url = "https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv"

In [3]:
df = pd.read_csv(url)
df.head()

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1016395 non-null  int64
 1   Id          1016395 non-null  int64
 2   Name        1016395 non-null  object
 3   Year        1016395 non-null  int64
 4   Gender      1016395 non-null  object
 5   State       1016395 non-null  object
 6   Count       1016395 non-null  int64
dtypes: int64(4), object(3)
memory usage: 54.3+ MB

### Delete the column 'Unnamed: 0' and 'Id'

In [5]:
df = df.drop(columns =['Unnamed: 0','Id'])

df.head()

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

### What year has the highest number of baby names in the dataset?

In [6]:
df.groupby('Year').sum().idxmax()

Name      2010
Gender    2007
State     2004
Count     2007
dtype: int64

### Are there more male or female names in the dataset?

In [7]:
df['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Group the dataset by name and assign to names

In [8]:
names = df.groupby("Name")["Count"].sum()
print(names)

Name
Aaban        12
Aadan        23
Aadarsh       5
Aaden      3426
Aadhav        6
           ...
Zyra         42
Zyrah        11
Zyren         6
Zyria        59
Zyriah       58
Name: Count, Length: 17632, dtype: int64

### How many different names exist in the dataset?

In [9]:
df['Name'].nunique()

17632

### What is the name with most occurrences?

In [10]:
df["Name"].value_counts().idxmax()

'Riley'

### How many different names have the least occurrences?

In [11]:
name_counts = df["Name"].value_counts()

(name_counts == name_counts.min()).sum()

np.int64(3682)

### What is the median name occurrence?

In [12]:
df["Name"].value_counts().median()

8.0

### What is the standard deviation of names?

In [13]:
df["Name"].value_counts().std()

122.02996350814088

### Get a summary with the mean, min, max, std and quartiles.

In [14]:
names.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64